### PR TITLE
fixes eventstfile missing getitem, len, constructor handles lists

### PR DESCRIPTION
**Pull request by jpata**
Events in eventstfile.py had some problems. 
- init provided a list of filenames, which TFile does not accept. => create TChain in case of list.
- iteration was broken because len and getitem were missing. => added

### CODE REVIEW

**Comment by jpata** [comment]
cc: @arizzi @gpetruc

**Comment by cbernet** [comment]
Hello!

There is a framework/chain.py class. 

Do you think you could use it instead of eventstfile, which I think is obsolete? 

See the heppycore example here: 
https://github.com/cbernet/cmssw/blob/heppy_7_2_2_patch2/PhysicsTools/HeppyCore/test/simple_example_cfg.py

Cheers, 

Colin

**Comment by jpata** [comment]
Thank you, Chain works fine. I was not aware of it and eventstfile being obsolete. Feel free to close.
Cheers

**Comment by cbernet** [comment]
Thanks for the feedback and sorry for the confusion. I will remove the obsolete file. 
Cheers!

**Pull request closed without merging**
