### PR TITLE
Add option for cmsRun preprocessor in Heppy

### PR DESCRIPTION
**Pull request by arizzi**
This adds the possibility (discussed in last CMGTools meeting) to run on the fly a cmsRun preprocessor (e.g. to fix the photons :-) ).
The output file should contain ONLY the newly computed stuff and does not need to copy the whole miniaod content because the files are then opened with two-files solution in fwlite.

in order to enable the preprocessor it is enough to:

```
from PhysicsTools.Heppy.utils.cmsswPreprocessor import CmsswPreprocessor
preprocessor = CmsswPreprocessor("makeAK5Jets.py")
```

and then to add the preprocessor in the looper config:

```
config = cfg.Config( components = selectedComponents,
                     sequence = sequence,
                     services = [],
                     events_class = Events,
                     preprocessor=preprocessor)  #add this line
```

### CODE REVIEW

**Comment by arizzi** [comment]
@gpetruc

**Comment by cbernet** [comment]
Hi Andrea, 

Could you please replace the use of kwargs by explicit parameters? 
Otherwise the user does not have a direct way to know which parameters are expected for the config object. 

Thanks, 

Colin

**Comment by cbernet** [comment]
Just to clarify: my request is not only about the config object, but about all kwargs introduced in this PR.
C

**Comment by arizzi** [comment]
hi colin, concerning the Config I can change it.
The other one I would not change it because we do not know how the interface of FWlite (or any other future wrapper)  would evolve (and is not under our control)
So this would allow to keep some flexibility.
If you really do not like kwargs I can just ad a single dictionary, "options" that must be always present and that is then handled internally in the various implementations of "Events"

**Comment by cbernet** [comment]
Thanks, Andrea. 

Config is indeed my main concern. 
I would like that the user to be able to use help so see the signature of the class methods, and in particular the constructor. In view of making the interface more user friendly, I will also add some docstrings at some point, and review the existing ones. 

For the other one, I agree with your proposal to add options as an explicit parameter. 
Could you then please add a doctstring explaining what is expected in options at the moment? 

Cheers, 

Colin

**Comment by arizzi** [comment]
updated.
Concerning the documentation, yes at some point it should be added, not just here but I would say in the "default" object analyzers so that people better understand which collections are used for what (i.e. which lepton collection is used for jet cleaning ? etc..)... perhaps we can have a chat the three of us in the next week to see where we stand, what else we want to include and how to go more public in the collaboration

**Comment by arizzi** [comment]
as the PR was not yet merged I added some fixes. The LHE analyzer one should speedup the processign for people using it

**Comment by arizzi** [comment]
...and found a bug introduced while fixing the signature of "Config"... fixed (and improved the examples)

**Pull request merged**
