### PR TITLE
Heppy updates from CMG

### PR DESCRIPTION
**Pull request by gpetruc**
Hello Colin, 

Here's all the updates to Heppy that we would like to make as part of porting CMGTools to Heppy in 7.2.X.
They include some improvements and new functionalities, and also bugfixes to things that had already been ported in Heppy by you or Andrea.
In the future we'll try to keep pull requests smaller, but in this case we wanted to first arrive at a point where we were able to reasonably run a CMGTools workflow.

@arizzi @mariadalfonso

### CODE REVIEW

**Comment by arizzi** [comment]
hi guys, concerning the **init**.py business I think the simple way out is to use **all**=[..list of modules..] so that the submodules are only loaded when import \* is done. I think in this case you do not need the explicit  imports inside init.py

Giovanni can/did you try?

**Comment by cbernet** [comment]
@arizzi sounds like a good solution.
One should test that analyzers can still be imported one by one using explicit imports.

**Comment by gpetruc** [comment]
it seems to give an error in PhysicsTools/HeppyCore/framework/config.py
because the imported objects don't have a `__module__` attribute.
Will go for the simpler `all.py` and we can change it later if we find a
better solution

**Comment by cbernet** [comment]
ok as soon as you push in this change I can merge.

**Comment by gpetruc** [comment]
pushed now the all.py

**Pull request merged**
