### PR TITLE
chain allows also LFN

### PR DESCRIPTION
**Pull request by jpata**
as #38 but against 744p4.

### CODE REVIEW

**Comment by cbernet** [comment]
Thanks! do you guarantee that chain is working? From what I can see that must be the case, but I'd like your confirmation that everything has been checked. If that's the case, I'll merge this right away in the CMSSW PR.

**Comment by jpata** [comment]
indeed, there was a mistake which didn't come out in previous tests, now fixed. is there a place for a unit test?

**Comment by cbernet** [comment]
You are very welcome to modify the existing unit test :-) 

Cheers, 

Colin

**Comment by jpata** [comment]
I've added a test for the new functionality which passes.

**Pull request merged**
