### PR TITLE
Heppy 7 4 7 allow batch at cern 

### PR DESCRIPTION
**Pull request by degrutto**
fix according to Colin request

### CODE REVIEW

**Comment by cbernet** [comment]
Hi Michele, 
lines 88 and 112 are now inconsistent
remote dir should start with /store at cern, not the root prefix.
Can you please fix?

**Comment by degrutto** [comment]
I guess the ''"root://eoscms.cern.ch//eos/cms/" is added by the batchmanager.py

**Comment by cbernet** [comment]
indirectly yes, it's added in eostools.py:

https://github.com/cbernet/cmssw/blob/heppy_7_4_7/PhysicsTools/HeppyCore/python/utils/batchmanager.py#L80

https://github.com/cbernet/cmssw/blob/heppy_7_4_7/PhysicsTools/HeppyCore/python/utils/eostools.py#L105

users are supposed to always use LFN. 
At least, it should be the case, from what I know and what I see in the code. 
Could you please try to do the change and test it? 

Then heppy_batch has a similar interface to cmsBatch (which takes /store in the -r option). 

Cheers, 
Colin

**Comment by degrutto** [comment]
Hi Colin,
I already tried before to have both line 80 and 105 to have just 
'/store/' and It does not work

   Michele

**Comment by cbernet** [comment]
that's weird. 
Can you debug that? 
Cheers, 
C

**Comment by degrutto** [comment]
Hi Colin,

how about that?

https://github.com/degrutto/cmssw/commit/6c8023e9bce6346f7313d40fc8111e4f35227e65

**Comment by cbernet** [comment]
After discussion, I merged this commit for now (private push, so this PR is not needed anymore)
https://github.com/degrutto/cmssw/commit/5d18d7ba58b6a177b9064f9f81341815ab32bcea

But a more general solution will have to be found. I'll do that. 
Cheers!

**Pull request closed without merging**
