### PR TITLE
CMG Heppy updates, 76X

### PR DESCRIPTION
**Pull request by gpetruc**
Includes an update to `CMSSW_7_6_3_patch2` since it's based on an Egamma branch that is rooted there.
A comparison of this PR with respect to Colin's heppy HEAD + `CMSSW_7_6_3_patch2` can bee seen at https://github.com/gpetruc/cmssw/compare/cbernet_heppy763_on_763patch2...cmg_heppy_76X_20160307

@arizzi

### CODE REVIEW

**Comment by arizzi** [comment]
we had to migrate to patch2 too because of new JETID recipe.

Colin can you switch to 763patch2 ?

**Comment by arizzi** [comment]
@cbernet are you going to merge this?

**Comment by cbernet** [comment]
yes I will

**Comment by cbernet** [comment]
Hi guys, I see that 764 is out since Tuesday, should I move to this release instead of 763patch2?

**Comment by arizzi** [comment]
@cbernet I'd rather prefer not to because it would imply migrating our stuff whil we want to launch asap a new ntuple production, but I'm flexible and can adapt.

**Comment by cbernet** [comment]
I agree let’s take our time. 
I now have an heppy branch for 763patch2, I still have to have a look in details at Giovanni’s PR on top of this one.
Should be no big deal, I’ll probably be able to merge everything this afternoon, and I’ll let you know asap

C

**Comment by cbernet** [comment]
This PR is included in my new branch, 
https://github.com/cbernet/cmssw/tree/heppy_7_6_3_patch2
So I'm closing it. 
From now on, please send me PR to the new branch.

Also, I would like to send a pull request to CMSSW soon in the 76X release stream. 
Do you want to add more things in the near future?

**Pull request closed without merging**
