### PR TITLE
Heppy updates and bugfixes from Mariarosaria

### PR DESCRIPTION
**Pull request by gpetruc**
Code is from @mariadalfonso, I only took care of making the pull request
@arizzi

### CODE REVIEW

**Comment by cbernet** [comment]
Hi all, 

I understood that this code is fixing the problem below that I reported last week. 
I merged it, and I still get the error. 
Could you please provide a fix? If not, I will simply comment out the 3 lines that rely on genParticleWithSourceType. 

Let me know. Cheers!

Colin 

collection GenTop is set to mcOnly since the type genParticle is mcOnly
collection GenBQuark is set to mcOnly since the type genParticle is mcOnly
Traceback (most recent call last):
  File "example_autofill.py", line 25, in <module>
    "genwzquarks"     : NTupleCollection("GenQuark",   genParticleWithSourceType, 6, help="Generated quarks from W/Z decays"),
NameError: name 'genParticleWithSourceType' is not defined

**Comment by arizzi** [comment]
I think the  "WithSource" was removed by giovanni.
genParticleWithSourceType -> genParticleType

should be enough.

btw giovanni is probably sending you another bugfix (unrelated) that is
worth having before the PR in CMSSW

**Comment by cbernet** [comment]
Ok, then I'll wait for both fixes. 
I didn't see the commits in which withSource have been removed. 

C

**Comment by arizzi** [comment]
I meant the type was removed from the supported types... the example was
never fixed... it is probably faster if you can fix it.. otherwise let me
know and I'll create a commit to cherrypick

**Comment by cbernet** [comment]
Ok, I’m fixing it now, removing withSource in these 3 lines. 

diff --git a/PhysicsTools/Heppy/test/example_autofill.py b/PhysicsTools/Heppy/test/example_autofill.py
index c496d3f..a1aae32 100644
--- a/PhysicsTools/Heppy/test/example_autofill.py
+++ b/PhysicsTools/Heppy/test/example_autofill.py
@@ -22,9 +22,9 @@ treeProducer= cfg.Analyzer(
                #dump of gen objects
                 "gentopquarks"    : NTupleCollection("GenTop",     genParticleType, 2, help="Generated top quarks from 
                 "genbquarks"      : NTupleCollection("GenBQuark",  genParticleType, 2, help="Generated bottom quarks fr
-                "genwzquarks"     : NTupleCollection("GenQuark",   genParticleWithSourceType, 6, help="Generated quarks
-                "genleps"         : NTupleCollection("GenLep",     genParticleWithSourceType, 6, help="Generated lepton
-                "gentauleps"      : NTupleCollection("GenLepFromTau", genParticleWithSourceType, 6, help="Generated lep
-                 "genwzquarks"     : NTupleCollection("GenQuark",   genParticleType, 6, help="Generated quarks from W/Z
-                 "genleps"         : NTupleCollection("GenLep",     genParticleType, 6, help="Generated leptons from W/
-                "gentauleps"      : NTupleCollection("GenLepFromTau", genParticleType, 6, help="Generated leptons from 

C

**Comment by gpetruc** [comment]
Hi Colin

The other change was to make it again possible to store by default all
floating point numbers as Float_t instead of Double_t
see https://github.com/CERN-PH-CMG/cmg-cmssw/pull/205
If you're doing changes, maybe you can cherry-pick the commit directly?
Otherwise I can make a PR for heppy later today

```
Giovanni
```

**Comment by cbernet** [comment]
Ok, I did the cherry pick. 
If you want to do more PRs, please tell me now as I’m about to freeze, port to the other releases, 
and do PRs to CMSSW. 

Colin

**Pull request merged**
