### PR TITLE
CMGTools Heppy 7_4_12 (end of 2015 version)

### PR DESCRIPTION
**Pull request by gpetruc**
Pull request of all CMG code to upstream Heppy, after merging the upstream heppy into the CMG heppy first to solve the conflict ( the reverse diff between the upstream heppy and the CMG is https://github.com/gpetruc/cmssw/pull/7 )

@arizzi @mariadalfonso

### CODE REVIEW

**Comment by gpetruc** [comment]
Updated with fixes to the pileup analyzer  (98deeb1)  and to the MET shifts on old 74X miniAOD (6d3c81c, which also saves the shifted mets by name and not just by integer enum key)

**Comment by cbernet** [comment]
All basic tests are passing. 

@arizzi would you prefer to test that everything is fine on the VHbb side on this branch before I port these modifications to 763?
https://github.com/cbernet/cmssw/tree/heppy_7_4_12

Or is it easier for you to do tests in 763 after the port? 

The thing is that the port from 74X to 76X is quite difficult and error-prone... So after I do the port of CMG's modifications, I'd prefer to close heppy_7_4_12 if possible. Let me both know if this could be a problem for you, and what are your plans concerning developments for 7_4_X. 

Cheers, 
Colin

**Comment by arizzi** [comment]
please go straight to 763, we will start from there and send further PR directly on 76X

**Comment by arizzi** [comment]
please let us know once the 76X branch is updated with this

**Pull request merged**
