### PR TITLE
Jpazzini heppy 7 4 4 patch4

### PR DESCRIPTION
**Pull request by jpazzini**

### CODE REVIEW

**Comment by cbernet** [comment]
Hi @arizzi @gpetruc 
Can you please confirm that these developments have not been put in place on your side already? 
C

**Comment by cbernet** [comment]
Hi @arizzi @gpetruc @emanueledimarco, 

I'm reviewing my opened pull requests, and I'm not sure what to do with this one. Could you please have a look? Did you set up these electron and photon ids in some other way already, maybe on the CMG side? Do you want me to merge it or not? 

Cheers, 

Colin

**Comment by jpazzini** [comment]
Hi,

from my side the pull request could be closed, as it now outdated. It 
referred to an old version of the 7_4_4_patch4, where some of the 
electron and photon cut based Ids were not implemented as suggested by 
the most up-to-date (at the time) EGamma POG twikis.
I guess things have already changed significantly since the 16th of june.

jacopo

**Comment by emanueledimarco** [comment]
Hi @cbernet, yes. I implemented the recommended WPs in the CMGTools repository some time ago and they were already merged in the 747 branch by @gpetruc. 
Now it is time to implement the recommended WPs tuned in Spring15...

**Comment by cbernet** [comment]
Thanks Jacopo and Emanule, I'm closing it.

**Pull request closed without merging**
