### PR TITLE
Current CMG Heppy (747-based)

### PR DESCRIPTION
**Pull request by gpetruc**
This is the current CMGTools 7_4_7 heppy head. I make a PR on this branch so you can see the differences, while I work at preparing the equivalent one for 7_4_12.
@arizzi @mariadalfonso

### CODE REVIEW

**Comment by cbernet** [comment]
Wow :-) 

Very nice piece of work, thanks to all contributors! 

I quickly browsed through all Heppy/ modifications and they look good. 
However, I cannot validate them, so I'm relying on the validation done by the CMG group.

I had a detailed look at the HeppyCore/ modifications and it’s all good. 

Do you need an up-to-date heppy_7_4_7 branch from me? 
if not, I will just wait for your 7_4_12 pull request.  

Cheers, 

Colin

**Comment by arizzi** [comment]
@jpata can you have a look merging it to our repo to see if it breaks something (I'll do some tests too but no time today)

**Comment by jpata** [comment]
OK I'll be able to late evening.

**Comment by arizzi** [comment]
it seems ok for VHbb side too. I had some conflict merging with our copy of #55 , but this is called mergeable here, so it should be ok

**Comment by cbernet** [comment]
Excellent, I will start working on the porting of the big PR from CMG

Colin

**Comment by arizzi** [comment]
Once you are done let me know so that I'll make for all your branches a commit adding a passAll option to the Json filter (so that it flags rather than filter)

**Comment by cbernet** [comment]
just merged the equivalent branch in 7_4_12

**Pull request closed without merging**
