### PR TITLE
Heppy: @veelken changes for TauAnalyzer

### PR DESCRIPTION
**Pull request by arizzi**
changes from @veelken  for tauAnalyzer

@gpetruc

### CODE REVIEW

**Comment by cbernet** [comment]
Hi guys, 

@steggema

The logic is still difficult to follow. 
As a result it’s actually quite hard for me to guess what’s going on without testing, 
but I will try. 

Note that I’m commenting on the whole code, which I think needs to be reviewed globally, not only on Christian’s additions. 

These are just small, easy to fix issues. 

L50-51:
- if the user did not provide the inclusive_decayModeID in the cfg, 
  or set it to False or None, continue is not hit and:
  we waste time in the following lines 
  I expect problems at L89 
  Did you test all possible cases for the conditions at L50 to make sure the code behaves as expected? 
  If the code is not supposed to be used without this parameter, an exception should be thrown. 
- please avoid long lines (use \ to break them)

L92: 
- there is no need for a second loop that only makes things less readable. 
  additional conditions and attributes can and should be placed within the first loop 

L94-108:
- why is it implied in the code that selected taus are selected according to loose conditions? (loose_decayModeID, loose_ptMin)
  -> remove loose_ everywhere.  

Cheers!

Colin

**Comment by gpetruc** [comment]
Adding @steggema to the thread since he also recently changed the tau analyzer on our side

**Comment by steggema** [comment]
What you usually want to do is:
1) require either decayModeFinding or decayModeFindingNewDMs (these are even required by default in miniAOD)
2) require an additional tau ID (which is often more of an isolation criterion, but may only be decayModeFinding if you want to study inclusive taus)
3) possibly require some anti-muon ID
4) possibly require some anti-electron ID

I introduced the previous version of L50-51 to be sure we have the possibility to do both 1) and 2), but didn't want to break old user code or code relying on having decayModeFinding already required at the miniAOD level and not having this parameter, which is why I added the "hasattr" part and added the comment in the default configuration. I agree it's cleaner to require the parameter. I don't see any problems with lines 89/90.

I agree with the comment about L92.

While I also tend to agree with the comment about L94-108, it's the same as in the LeptonAnalyzer, so I think it's a priori a good idea to have them harmonised.

**Comment by cbernet** [comment]
Hi again, 

Jan and I just had a phone call. 
I had misunderstood the code at L50 and 89. I thought the same tauID was tested in both case. 
In fact not, so I’m fine with the code as it is now. 

We both agree that the second loop should be removed, and that loose_ should be removed from the TauAnalyzer, L94-108. 
Otherwise we can end up with things like: 

loose_tauID = "byTightCombinedIsolationDeltaBetaCorr3Hits »,

We would propose to also remove the loose_ from the LeptonAnalyzer to keep things uniform. What do you guys think? 

Cheers, 

Colin

**Comment by cbernet** [comment]
Hi Andrea and Christian,
I'm closing this PR assuming that the changes have been included in some other PR. If not, just comment.

**Comment by arizzi** [comment]
@veelken can you check?

**Comment by veelken** [comment]
I don't see the changes included in CMSSW_7_6_0_pre3 yet:
    http://cmslxr.fnal.gov/lxr/source/PhysicsTools/Heppy/python/analyzers/objects/TauAnalyzer.py?v=CMSSW_7_6_0_pre3
so I think the PR still needs to be merged.

**Comment by cbernet** [comment]
In fact you should check in https://github.com/cbernet/cmssw/tree/heppy_7_4_7. 
If the code still needs to be merged, could you please open a PR to this branch? 
Thanks! 
C

**Comment by veelken** [comment]
Hi Colin,

the version included in heppy 7_4_7 is up-to-date:
    https://github.com/cbernet/cmssw/blob/heppy_7_4_7/PhysicsTools/Heppy/python/analyzers/objects/TauAnalyzer.py

Can you remind me who is in charge of making sure that these changes get propagated to CMSSW 7_5_X and 7_6_x ? 

Thank you,

Christian

**Comment by cbernet** [comment]
Thanks for the confirmation!
This pull request should thus stay closed. 

I am in charge of managing the pull requests to CMSSW. 
The decision to make a PR is basically taken by Giovanni, Andrea and myself,
and based on the needs of our users. 

We are now in the process of syncing heppy for 747. 
When done, I will do a PR for a later 74X release, for legacy, 
and I will start porting heppy to the 75X release cycle. 
We have no plans for 76X at the moment. For what do you need it? 

Cheers!

C

**Comment by veelken** [comment]
Hi Colin,

thank you for the information.
I will probably not be using CMSSW 7_6_x anytime soon. I was just surprised that the fix is not included in CMSSW 7_6_0_pre3 yet and just wanted to make sure that I understand the procedure, so that the PR does not get lost.

Cheers,

Christian

**Pull request closed without merging**
