### PR TITLE
Heppy 7 4 5 allow batch at cern to write to eos mdg

### PR DESCRIPTION
**Pull request by degrutto**
one can now write to cmst3 (if splitFactor >1) with the batch commands something like

heppy_batch.py -r /store/group/cmst3/user/username/dirname -o dirname  heppyanalysis.py  batch LXPLUS  -b 'bsub -q blahblahblah < batchScript.sh'

### CODE REVIEW

**Comment by cbernet** [comment]
Hi Michele, 
Could you please answer my questions, and let me know if you still want to merge this code? 
If that's the case, please move your PR to the current branch, heppy_747
Thanks,
Colin

**Comment by degrutto** [comment]
Hi Colin,
sorry I have completely missed the first email, 
in principle what you do ask is simple, I hope to have a look at it tomorrow 

cheers

```
  Michele
```

**Comment by degrutto** [comment]
Hi Colin, 
sorry for the delay,
please have a look at 
https://github.com/cbernet/cmssw/pull/53

the check if the dir exist and failure in case it does not it is already done in the HeppyCore, see for example  below...

######################
Unable to stat /store2/group/cmst3/user/degrutto/SingleMuonRun2_50ns_testBatch; No such file or directory (errc=2) (No such file or directory)

Command (['/afs/cern.ch/project/eos/installation/pro/bin/eos.select', 'mkdir', '-p', '/store2/group/cmst3/user/degrutto/SingleMuonRun2_50ns_testBatch']) failed with return code: 1
error: unable to create directory (errc=1) (Operation not permitted)

Traceback (most recent call last):
  File "/afs/cern.ch/work/d/degrutto/private/vhbbHeppy74X/CMSSW_7_4_7/bin/slc6_amd64_gcc491/heppy_batch.py", line 309, in <module>
    options, args = batchManager.ParseOptions()
  File "/afs/cern.ch/work/d/degrutto/private/vhbbHeppy74X/CMSSW_7_4_7/python/PhysicsTools/HeppyCore/utils/batchmanager.py", line 90, in ParseOptions
    castortools.createEOSDir( self.remoteOutputDir_ )
  File "/afs/cern.ch/work/d/degrutto/private/vhbbHeppy74X/CMSSW_7_4_7/python/PhysicsTools/HeppyCore/utils/eostools.py", line 243, in createEOSDir
    raise OSError('cannot create directory '+ path)
OSError: cannot create directory root://eoscms.cern.ch//eos/cms/store2/group/cmst3/user/degrutto/SingleMuonRun2_50ns_testBatch
[degrutto@lxplus0006 test]$ heppy_batch.

**Comment by cbernet** [comment]
closing as obsolete. the change has been merged, though. 
except for https://github.com/degrutto/cmssw/commit/a2eb4551432105d33e8c1743ecaa873daf64a5b5 which is anyway not related to this PR

**Pull request closed without merging**
