### PR TITLE
Heppy updates from CMG

### PR DESCRIPTION
**Pull request by gpetruc**
- add cross section from the component into the trees
- update lepton isolations in analyzer
- fix application of jet energy corrections
- allow fine job splitting (N jobs on the same file)

### CODE REVIEW

**Comment by arizzi** [comment]
and it makes no sense on data...

**Comment by arizzi** [comment]
or at least:

```
-bash-4.1$ git diff
diff --git a/PhysicsTools/Heppy/python/analyzers/core/AutoFillTreeProducer.py b/PhysicsTools/Heppy/python/analyzers/core/AutoFillTreeProducer.py
index d0c7a0e..ff04bde 100644
--- a/PhysicsTools/Heppy/python/analyzers/core/AutoFillTreeProducer.py
+++ b/PhysicsTools/Heppy/python/analyzers/core/AutoFillTreeProducer.py
@@ -50,7 +50,8 @@ class AutoFillTreeProducer( TreeAnalyzerNumpy ):
         tr.var('lumi', int, storageType="i")
         tr.var('evt', int, storageType="i")
         tr.var('isData', int)
-        tr.var('xsec', float)
+        if hasattr(self.cfg_comp,"xSection"):
+            tr.var('xsec', float)

  #       self.triggerBitCheckers = []
  #       if hasattr(self.cfg_ana, 'triggerBits'):
@@ -109,7 +110,8 @@ class AutoFillTreeProducer( TreeAnalyzerNumpy ):
         tr.fill('lumi',event.input.eventAuxiliary().id().luminosityBlock())
         tr.fill('evt', event.input.eventAuxiliary().id().event())    
         tr.fill('isData', 0 if isMC else 1)
-        tr.fill('xsec',self.cfg_comp.xSection)
+        if hasattr(self.cfg_comp,"xSection"):
+            tr.fill('xsec',self.cfg_comp.xSection)

 #       triggerResults = self.handles['TriggerResults'].product()
 #       for T,TC in self.triggerBitCheckers:
```

**Comment by cbernet** [comment]
I would agree with @arizzi . The other thing I was thinking is that xsection is typically applied easily at a later stage, for greater flexibility. if you have it in the tree and want to change it, you need to have another way to override it later on, so I'm not sure it's useful at all to store it in the tree.
What I'm doing is to load the components in the analysis macro that runs on the flat tree.

**Comment by mariadalfonso** [comment]
I agree to add the protection for the DATA.

In practice it's very useful to have the xSection stored.
Once we have the total number of MC events we runned on (pre-skim), each events can get a trivial weight to scale to X fb-1.
To have a self contained tree, what people do is to post-process the files and add the xsection and nTotalEvent by hand now. 
So would avoid to do this manual second step.

Maria

**Comment by gpetruc** [comment]
Ciao,

I agree that the implementation is wrong, it was obviously supposed to be
applied only on MC, I didn't check the commit before propagating it to
Heppy.
Will fix in the next PR today

For TTH we have always read the cross section from an external file, but
too many people where complaining that it was too complicated for them to
do it so we added it (space wise it costs ~zero, since it's the same in all
events)

```
Giovanni
```

**Comment by arizzi** [comment]
@mariadalfonso if you run with a TFileService having name "outputfile" the TreeProducer will book the tree in such file instead of creating its own.
Then you can access it from a dedicated analyzer filling all the metadata you want, including histos etc..

```
from PhysicsTools.HeppyCore.framework.services.tfile import TFileService 
output_service = cfg.Service(
      TFileService,
      'outputfile',
      name="outputfile",
      fname='tree.root',
      option='recreate'
    )
```

**Pull request merged**
